image:
  repository: ghcr.io/faustvii/plexanilistsync
  pullPolicy: IfNotPresent
  tag: 3.0.0@sha256:59a7bf9800db92e9a9bc1b3a90bab9d45c4dc4c7d3d2a2bed498722f8dbf1ab1

service:
  main:
    ports:
      main:
        port: 40001
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/app/appsettings.json"

portal:
  enabled: true
