image:
  registry: docker.io
  repository: turzam/ark
  tag: latest
  pullSecrets: []
  pullPolicy: IfNotPresent

portal:
  enabled: false

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

secretEnv:
  rconPassword:
env:
  am_arkNoPortDecrement: true
  serverName: "Ark TrueNas"
  map: "TheIsland"
  maxPlayers: 70
  password: ""
  tz: ""
  gid: ""
  uid: ""

persistence:
  game:
    mountPath: "/ark"

service:
  main:
    ports:
      ark:
        targetPort: 7778
        port: 7778
        protocol: UDP
      arkTcp:
        targetPort: 7778
        port: 7778
        protocol: TCP
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 32330
        targetPort: 32330
        protocol: TCP
  query:
    enabled: true
    ports:
      query:
        enabled: true
        port: 27015
        targetPort: 27015
        protocol: UDP

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

resources:
  limits:
    cpu: 1.5
    memory: 8Gi
  requests:
    cpu: 1
    memory: 6Gi
