image:
  repository: ghcr.io/faustvii/plexanilistsync
  pullPolicy: IfNotPresent
  tag: 3.7.1@sha256:ef54f215533a084b1f7813dafa603b5b40d5d0a483bc359ac33097abfc197dc0

service:
  main:
    ports:
      main:
        port: 40001
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/app/appsettings.json"

portal:
  enabled: true
