image:
  repository: ghcr.io/faustvii/plexanilistsync
  pullPolicy: IfNotPresent
  tag: 3.2.0@sha256:478baf531e24dfceb15d989dd57d80a31ea9f1efdab69ecaa10b1de8bd3d2368

service:
  main:
    ports:
      main:
        port: 40001
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/app/appsettings.json"

portal:
  enabled: true
