name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
# permissions:
#   contents: write # to be able to publish a GitHub release
#   packages: write # to be able to publish a package
#   pull-requests: write # to be able to comment on released pull requests
#   issues: write # to be able to comment on released issues

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@59a07fba98dcaea797f2d50ec0c478321c250b41 # tag=v32.180.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
