image:
  repository: ghcr.io/faustvii/plexanilistsync
  pullPolicy: IfNotPresent
  tag: 3.2.0@sha256:cb08aaf209fbeb88db19348eaedda4e6c5b37a1b17f55904cadfe1c0a2ebb457

service:
  main:
    ports:
      main:
        port: 40001
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/app/appsettings.json"

portal:
  enabled: true
